### PR TITLE
Fix #619: Remove ports from shared YouTube links

### LINKED ISSUE #619: Sharing a video as a Youtube link includes port of the used Invidious instance
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/yattee/yattee/issues) and I haven't found bug report like this

### Current Behavior

I use Yattee with an Invidious instance that runs on port 4000. When I open a video, tap Share, choose Youtube link the link included the port 4000, so http://youtube.com:4000/something. 

### Expected Behavior

Youtube link should always be correct, without any port.

### Device & OS Version

iPhone 15

### App Build

174

### App Settings

Logged into a local Invidious instance running on port 4000.

### Crash log

_No response_

### Screenshots, Videos and other files

_No response_

### PR DESCRIPTION
**Pull request by 0x000C**
Issue #619 describes how when the app is connected to a frontend hosted on a non-standard port, that port gets added to shared YouTube links.

This change removes ports from shared YouTube links.

### CODE REVIEW

**Comment by stonerl** [comment]
To me this looks more like a workaround. It seems that the frontendHost gets constructed with the e.g. the invidious instance and only the url part is changed to YouTube afterwards.

A better solution would be to construct the frontendHost correctly in the first place.

Just my 2 cents, though …

**Comment by 0x000C** [comment]
I updated the shareURL function and it's caller to handle schemas and ports correctly, and more generically than before.

It no longer always uses the active instance's schema and port to form the shared URL, and instead can receive and parse a URL string for that information.

File: Model/Applications/VideosAPI.swift [hunk 1]
```diff
@@ -108,15 +108,19 @@ extension VideosAPI {
...
 
-    func shareURL(_ item: ContentItem, frontendHost: String? = nil, time: CMTime? = nil) -> URL? {
-        guard let frontendHost = frontendHost ?? account?.instance?.frontendHost,
-              var urlComponents = account?.instance?.urlComponents
-        else {
+    func shareURL(_ item: ContentItem, frontendURL: String? = nil, time: CMTime? = nil) -> URL? {
+        var urlComponents: URLComponents?
+        if let frontendURLString: String = frontendURL,
+            let frontendURL: URL = URL(string: frontendURLString) {
+            urlComponents = URLComponents(URL: frontendURL, resolvingAgainstBaseURL: false)
```
Comment (arekf) [inline Model/Applications/VideosAPI.swift:115]:
```suggestion
    func shareURL(_ item: ContentItem, frontendURLString: String? = nil, time: CMTime? = nil) -> URL? {
        var urlComponents: URLComponents?
        if let frontendURLString,
            let frontendURL = URL(string: frontendURLString) {
            urlComponents = URLComponents(URL: frontendURL, resolvingAgainstBaseURL: false)
```

File: Model/Applications/VideosAPI.swift [hunk 2]
```diff
@@ -108,15 +108,19 @@ extension VideosAPI {
...
+        } else if let instanceComponents = account?.instance?.urlComponents {
+            urlComponents = instanceComponents
+        }
+        
+        guard var urlComponents: URLComponents = urlComponents else {
```
Comment (arekf) [inline Model/Applications/VideosAPI.swift:120]:
```suggestion
        guard var urlComponents else {
```

**Review by arekf — CHANGES_REQUESTED** [review]
Thanks, could you please take care of small style changes to not to use explicit types when possible?
